steps:
  - name: 'golangci/golangci-lint:v1.24.0'
    env: ['GOGC=5']
    args: ['golangci-lint', 'run']
  - name: 'golang:1.14.2-alpine'
    args: ['go', 'test', './...']
  - name: 'golang:1.14.2-alpine'
    args: ['go', 'build', '-o', 'wireguard-controller', 'github.com/mrincompetent/wireguard-controller/cmd/controller']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'quay.io/mrincompetent/wireguard-controller:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login -u="$$QUAY_USERNAME" -p="$$QUAY_PASSWORD" quay.io']
    secretEnv: ['QUAY_USERNAME', 'QUAY_PASSWORD']
images:
  - 'quay.io/mrincompetent/wireguard-controller:$COMMIT_SHA'
options:
  env: ['CGO_ENABLED=0']
secrets:
  - kmsKeyName: projects/henrik-221510/locations/global/keyRings/build-wireguard-controller/cryptoKeys/enc-key1
    secretEnv:
      QUAY_USERNAME: "CiQAqIaQX1qwrkMASmZreTJk1+Xll/lC2Q2si60QshzFy7yujAYSSQB3Xg5+kqphmOE8i3huzbv55g9qxR0kk+kQYut9XhT4x+Gr2l4IGlmJC7CDNLR2OypcgFf/1xdE15kNWRhggtoCvYdkk6GNeUo="
      QUAY_PASSWORD: "CiQAqIaQX6j17VjTrVSf3XdWWVWdFcreR3ckos09PtPOIyAAeZ8SaAB3Xg5+jOqymCOuVuBeAIBNuz1/WDCmUdyMW/1BpBwRlbC16Qh62DcP1WTxkkCjO7Exjc8ImwcY31/X0ud6nY5TxcTuG5iGn7YCWcf3ITbfwWPpG9Z/eSoqyxQ7mm5LJ6e0SYzRgsmz"
