run:
  tests: false
  timeout: 10m
service:
  golangci-lint-version: 1.32.2
linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - exhaustivestruct
    - gosec
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gci:
    local-prefixes: github.com/mrincompetent/wireguard-controller
  misspell:
    locale: US
  lll:
    line-length: 160
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  funlen:
    lines: 150
    statements: 100
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/pkg/errors
    packages-with-error-messages:
      github.com/pkg/errors: "errors should be wrapped using fmt.Errorf('something failed: %w', err)"
